language: java
jdk: oraclejdk7
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pproduction
- mvn test -B

deploy:
  provider: s3
  access_key_id:
    secure: "r4rfQSCKUhV8SVry9qK6en7aGDyag2whOR7GKFJ75SIfTRZZeUkz11qV27zEGyWke6isZOMsHS7L0A2Szw20+NPolYCl5IcI37uwrwrO2waagcUsgWqkJmZ21EfgF+0myIPmBrWnxae6BOcTuVmTcZycZOMS8lMgmtZxdpEjRu4="
  secret_access_key:
    secure: "zOnw7iU76zkrYqwIXkI49FxVPRsW/JMYSXnNw83IVeiG43pR5V9MP46fscK1xBaqwzfwfYbpMiq+jT0I6/FXsREGI5gWYUfQ8p9ibleLYKKXMZG6EAun4Nq6j9xGCr/m4ox+WoJU8W7KHNN/DUQb6dIVgUX7M3Lx1Zqt8wo44fk="
  bucket: public-maven-repository
  local-dir: /home/travis/.m2/repository/com/forter/riemann-storm-monitor/
  upload-dir: repository/com/forter/riemann-storm-monitor
  skip_cleanup: true
  on:
    branch: prod
    tags: true
