language: java
jdk: oraclejdk7
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pproduction
- mvn test -B

deploy:
  provider: s3
  access_key_id:
    secure: "r4rfQSCKUhV8SVry9qK6en7aGDyag2whOR7GKFJ75SIfTRZZeUkz11qV27zEGyWke6isZOMsHS7L0A2Szw20+NPolYCl5IcI37uwrwrO2waagcUsgWqkJmZ21EfgF+0myIPmBrWnxae6BOcTuVmTcZycZOMS8lMgmtZxdpEjRu4="
  secret_access_key:
    secure: "yqFueGXnmdZMJRO/0/2lo2H2ZTBBwFtT4XJUzJvkgqxHUOvaE1I/hMw6MbyDgsMRPb5tqbmPeNyleVeg18N/ph9Mof/ak+KX35zXUNjh1wwlSK0AVfVtnbjPiJeKFXvAlX67W7oxvtR8fw6FieQB+A0/zm4g7kPKxOupPcAsYYI="
  bucket: oss.forter.com
  local-dir: /home/travis/.m2/repository/com/forter/riemann-storm-monitor/
  upload-dir: repository/com/forter/riemann-storm-monitor
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
